name: Build Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: QEMU Setup
        uses: docker/setup-qemu-action@v2
      -
        name: Docker-Buildx Setup
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64/v8,linux/amd64
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64/v8,linux/amd64
          context: ./ip-address-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ip-address-app:latest

